[default]

[[directives]]
name = "simple resize"
urlpattern = "/convert/e/([a-z]+)/w/([0-9]+)/h/([0-9]+)/(.+)"
engine = "$engine"
[directives.vars]
"$engine" = "$1"
"$dw" = "$2"
"$dh" = "$3"
"$filepath" = "$4"
[directives.src]
type = "fs"
root = "./bench/images"
path = "$filepath"
[directives.out]
format = "jpeg"
quality = 100
cache = "30s"
[[directives.converts]]
type = "resize"
parameters = {dw = "$dw", dh = "$dh"}
